use db3;
CREATE TABLE ipg_ez (
    id INT NOT NULL AUTO_INCREMENT,
    Site VARCHAR(255),
    BL_Number VARCHAR(255),
    Truck_Appointment_Date DATE,
    BL_Weight DECIMAL(10,2),
    Freight_Amount DECIMAL(10,2),
    Truck_Appt_Time TIME,
    Pickup_Date DATE,
    State VARCHAR(255),
    Ship_to_City VARCHAR(255),
    Ship_to_Customer VARCHAR(255),
    Order_Number VARCHAR(255),
    Order_Item VARCHAR(255),
    CSR VARCHAR(255),
    Freight_Term VARCHAR(255),
    Require_Date DATE,
    Schedule_Date DATE,
    Unshipped_Weight DECIMAL(10,2),
    Product_Code VARCHAR(255),
    Pick_Weight DECIMAL(10,2),
    Number_of_Pallet INT,
    Pickup_By VARCHAR(255),
    Change_Date DATE,
    Carrier_ID VARCHAR(255),
    Arrange_By VARCHAR(255),
    Unit_Freight DECIMAL(10,2),
    Waybill_Number VARCHAR(255),
    Sales_Code VARCHAR(255),
    Transportation_Code VARCHAR(255),
    Transaction_Type VARCHAR(255),
    Product_Group VARCHAR(255),
    uploaded_date_time DATETIME,
    rpt_run_date DATE,
    rpt_run_time TIME,
    file_name VARCHAR(255),
    file_size INT,
    PRIMARY KEY (id)
);
